### ISSUE TITLE
Issue with dictionary-baed text analysis

### ISSUE THREAD

**Issue by coolsteed** [cbail/textasdata#1]
Under the section "Dictionary-Based Quantitative Text Analysis"
Issues in the following code chunk
```{r}
economic_dictionary<-c("economy","unemployment","trade","tariffs")

library(stringr)
economic_tweets<-trumptweets[str_detect(trumptweets$text, economic_dictionary),]
head(economic_tweets$text)
```
The code here is not accurate. Str_detect here does not exact match, it won't matter in this specific case, but if one want to decide whether Trump is cat or dog people. This code won't help. For example,  if the dict contains "cat", this code will capture every tweet from Trump containing "education". 

The code modification I propose might fit more general application. 
```{r}
economic_tweets<-trumptweets %>% 
filter(text, paste0(economic_dictionary, "\\b", collapse = "|")))
```

**Comment by cbail** [comment]
Great suggestion thanks.
